CREATE TABLE snippets (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    state INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    seed_text TEXT NOT NULL,
    generated_text TEXT
);
